# CORE MAKEFILE
#

CORE_BUILD_DIR := ../../build
include $(CORE_BUILD_DIR)/definitions.mk

OBJ_FILES = pov.o
TARGET  = pov
TARGETS = $(TARGET)
MCU     = attiny85
F_CPU   = 8000000UL

include $(CORE_BUILD_DIR)/core.mk
