# CORE MAKEFILE
#

CORE_BUILD_DIR := ../../build
include $(CORE_BUILD_DIR)/definitions.mk

OBJ_FILES = pov.o
TARGET  = pov
TARGETS = $(TARGET)
MCU     = atmega32u4
F_CPU   = 1000000UL

include $(CORE_BUILD_DIR)/core.mk
